spring:
  application:
    name: bolg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 121891
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.lmy: info
  file: log/blog-pro.log
server:
  port: 8081
